target-version = "py39"

[lint]
extend-select = ["PLE", "I", "TID251", "RET", "TC", "UP"]
ignore = ["E501"]

[lint.flake8-tidy-imports.banned-api]
json.msg = "Use orjson instead"

[lint.per-file-ignores]
"tests/*" = ["TID251"]
