name: Nightly add-on Release
on:
  push:
    branches:
      - nightly
  schedule:
    - cron: "0 0 * * 1"

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/glutanimate/anki-addon-builder.git@4039b5bb743773a18cb2911e6dd38fa1e3f65982
          python -m pip install pyqt5

      - name: Create .ankiaddon package
        run: aab build -d ankiweb

      - name: Recreate Nightly Tag
        run: |
          git tag -f nightly-release
          git push origin refs/tags/nightly-release --force

      - name: Update Rolling Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-release
          name: "Nightly Build"
          body: |
            **Automated Nightly Build**
            _Last updated: ${{ github.event.head_commit.timestamp || 'Scheduled Run' }} (Commit: ${{ github.sha }})_
          prerelease: true
          files: build/*.ankiaddon
